language: node_js
node_js:
  - "node"

script:
  - ./node_modules/hexo/bin/hexo generate
  - cp README.md public/README.md

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  repo: git@github.com:ganlvtech/ganlvtech.github.io.git
  target-branch: master
  on:
    branch: master
