language: node_js
node_js:
  - "node"

branches:
  only:
    - dev

script:
  - ./node_modules/hexo/bin/hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: dev
